### ISSUE TITLE
Centralize the adding of models 

### ISSUE THREAD

**Issue by animalnots** [animalnots/BetterChatGPT-PLUS#16]
see
![image](https://github.com/animalnots/BetterChatGPT-VISION/assets/4728576/b78504ba-023b-48d7-83d8-210917c83fef)

https://github.com/ztjhz/BetterChatGPT/issues/589

**Comment by animalnots** [comment]
also this
https://github.com/ztjhz/BetterChatGPT/issues/574

**Comment by animalnots** [comment]
also https://github.com/ztjhz/BetterChatGPT/issues/528

**Comment by jbash** [comment]
OpenAI itself doesn't return any useful metadata from the "/v1/models" endpoint, but OpenRouter *does* and seems to have real traction (see https://openrouter.ai/api/v1/models). If you harmonized the schema you used for this with the schema that OpenRouter uses, you could eventually extend BetterChatGPT to dynamically discover all of the available models *and* their features. Then if LocalAI got on board...

**Comment by animalnots** [comment]
added in https://github.com/animalnots/BetterChatGPT-PLUS/releases/tag/v1.6.0
