### ISSUE TITLE
change title

### ISSUE THREAD

**Issue by coding-garden-1** [animalnots/BetterChatGPT-PLUS#26]
not an actual issue but a suggestion which ur free to leave or take: maybe something like BetterChatGPT-Plus would be better (tho kinda wordy) b.c. VIsion is only one of the epic new features youve add1ed. i love this thing so much tho. i did notice some slowdown with gpt-4o-mini but that might be gpts servers

**Comment by animalnots** [comment]
Done! Thanks for the suggestion.
