### ISSUE TITLE
Imported chats from `https://bettergpt.chat/` to `https://zapzatron.github.io/BetterChatGPT-PLUS/` and now only white screen is displayed 

### ISSUE THREAD

**Issue by Zapzatron** [animalnots/BetterChatGPT-PLUS#29]
Imported chats from `https://bettergpt.chat/` to `https://zapzatron.github.io/BetterChatGPT-PLUS/` and now only white screen is displayed 
![image](https://github.com/user-attachments/assets/821f65f0-4a93-4326-a6a7-a9601c06a59c)

**Comment by animalnots** [comment]
Thanks for reporting this. I will have a closer look at it a bit later.

**Comment by Zapzatron** [comment]
Also after I downloaded the json of chats, the text is no longer generated, requests to the API go, but the text is not output.
Most likely this problem is also in BetterChatGPT-PLUS

**Comment by animalnots** [comment]
fixed in https://github.com/animalnots/BetterChatGPT-PLUS/releases/tag/v1.5.0
