### ISSUE TITLE
Can you make the photo output larger so you can see the text on the photo?

### ISSUE THREAD

**Issue by Zapzatron** [animalnots/BetterChatGPT-PLUS#31]
![image](https://github.com/user-attachments/assets/f7c1e392-c68e-4a19-a7c9-7347daa5ca0d)
Can you make the photo output larger so you can see the text on the photo?

**Comment by animalnots** [comment]
can probably implement "zoom on click"

**Comment by animalnots** [comment]
https://github.com/animalnots/BetterChatGPT-PLUS/releases/tag/v1.5.0
