### ISSUE TITLE
Make it possible to choose which model to use for automatic generation of chat title in the list.

### ISSUE THREAD

**Issue by Zapzatron** [animalnots/BetterChatGPT-PLUS#32]
Make it possible to choose which model to use for automatic generation of chat title in the list.
For example, instead of `gpt-3.5-turbo` use `gpt-4o-mini`.
By default, `gpt-3.5-turbo` is used to generate the chat title.

https://betterchatgpt.canny.io/feature-requests/p/make-it-possible-to-choose-which-model-to-use-to-create-the-chat-title

**Comment by Zapzatron** [comment]
@animalnots
Do I understand correctly that now the same model is used for generating the title as for generating the main text?
If so, can you make it possible to separately select the model for automatic title generation. For example, in `default chat config`, add a model selection for header generation. So that you can call, for example, `gpt-4o` for main text generation, and `gpt-4o-mini` for automatic title generation.
![image](https://github.com/user-attachments/assets/b2183ab5-ba9c-4e8d-a31e-c22b9303533a)

**Comment by animalnots** [comment]
added in https://github.com/animalnots/BetterChatGPT-PLUS/releases/tag/v1.5.0
