### ISSUE TITLE
Image is ignored / not sent when it's the only content in new chat

### ISSUE THREAD

**Issue by animalnots** [animalnots/BetterChatGPT-PLUS#39]
Story:
As a user, when I send only an image(no text) I expect the LLM to return info about the image

Actual result:
I get a response which indicates that the image is not being sent/processed by the LLM
<img width="656" alt="image" src="https://github.com/user-attachments/assets/e34cc375-ec87-4342-a9aa-54379264b696">

Steps to replicate:
1) create new chat
2) select image model
3) insert image only from clipboard (no text)
4) send
5) the answer doesn't include any info about the image

**Comment by Zapzatron** [comment]
![image](https://github.com/user-attachments/assets/b18725d0-6661-4595-ae12-2cf688ae812a)
It works for me. Inserted it from the clipboard.

**Comment by Zapzatron** [comment]
Sent a picture in 4k and it didn't work.
![image](https://github.com/user-attachments/assets/05fccbfa-3b2d-40b8-912b-2d3ec359d47d)

**Comment by animalnots** [comment]
if you send it with text, it work, it only doesnt work when it's the image and nothing else (no text or spaces)

**Comment by animalnots** [comment]
fixed in https://github.com/animalnots/BetterChatGPT-PLUS/releases/tag/v1.6.0
