### ISSUE TITLE
No model list for selecting the required model

### ISSUE THREAD

**Issue by Zapzatron** [animalnots/BetterChatGPT-PLUS#42]
No model list for selecting the required model
![image](https://github.com/user-attachments/assets/9e4297ec-385e-4043-9ae1-9e0bf94f77d4)

**Comment by animalnots** [comment]
looking into it

**Comment by animalnots** [comment]
cheers, fixed https://github.com/animalnots/BetterChatGPT-PLUS/releases/tag/v1.7.0
