### ISSUE TITLE
Failed to execute 'setItem' on 'Storage': Setting the value of 'free-chat-gpt' exceeded the quota.

### ISSUE THREAD

**Issue by Zapzatron** [animalnots/BetterChatGPT-PLUS#44]
I'm not using any `free-chat-gpt`.
Before I got the error `Failed to execute 'setItem' on 'Storage': Setting the value of 'free-chat-gpt' exceeded the quota.`  I sent a `.txt` file to where the photo should be uploaded.
I sent the `.txt` to test what happens if you send an unsupported file extension.
![image](https://github.com/user-attachments/assets/797c6b1c-9867-4917-99c2-0590f6d42a11)

**Comment by Zapzatron** [comment]
The https://github.com/ztjhz/BetterChatGPT/issues/148#issuecomment-1486059614 says that the browser storage capacity is locally exceeded, but I only have two chats in this profile.
![image](https://github.com/user-attachments/assets/7b7c6bd6-639f-4af8-b476-ded665409512)

**Comment by animalnots** [comment]
Updated behaviour so that it warns the user if the file that is trying to be saved is too big for the storage.
https://github.com/animalnots/BetterChatGPT-PLUS/releases/tag/v1.8.0
