### ISSUE TITLE
I can't open your website they are blank

### ISSUE THREAD

**Issue by steveholdjin** [animalnots/BetterChatGPT-PLUS#50]
I can't open your website they are blank I also tried downloading the app they don't work
![20240830145929](https://github.com/user-attachments/assets/2d8c27b1-187c-455d-b975-3e5334a85bfa)

**Comment by animalnots** [comment]
thanks for reporting, looking into it

**Comment by animalnots** [comment]
fixed

**Comment by animalnots** [comment]
https://github.com/animalnots/BetterChatGPT-PLUS/releases/tag/v1.8.1
