### ISSUE TITLE
User and System change places in the chat.

### ISSUE THREAD

**Issue by Zapzatron** [animalnots/BetterChatGPT-PLUS#55]
At the first request everything is fine, but if you make a second request in the same chat, the first user message changes places with system. And they cannot be moved with arrows.
![image](https://github.com/user-attachments/assets/3f1b90e1-bedc-4956-95c7-e5ebec4d67a9)

**Comment by animalnots** [comment]
Can you let me know about the exact steps to replicate the issue, please?

**Comment by Zapzatron** [comment]
1. Go to `https://animalnots.github.io/BetterChatGPT-PLUS/`
2. Send the first text to gpt
3. Receive a text from gpt
4. Send the second text to gpt

**Comment by animalnots** [comment]
interesting, thanks. From the looks of the json it's just the visual inconsistency and the order of the messages should be correct when sent to the API. I'll check out why it's happening.

**Comment by animalnots** [comment]
fixed https://github.com/animalnots/BetterChatGPT-PLUS/releases/tag/v1.8.3
thanks
