### ISSUE TITLE
OpenAI o1 models - "Unsupported value: 'stream' does not support true with this model."

### ISSUE THREAD

**Issue by lindoalex577** [animalnots/BetterChatGPT-PLUS#62]
When requesting on o1 models, this error shows up:

```
{
  "error": {
    "message": "Unsupported value: 'stream' does not support true with this model. Only the default (false) value is supported.",
    "type": "invalid_request_error",
    "param": "stream",
    "code": "unsupported_value"
  }
}
```

According to https://platform.openai.com/docs/guides/reasoning/beta-limitations, there's currently no support for streaming on the o1 models as of this moment.

**Comment by animalnots** [comment]
Thanks for reporting, will look into that today

**Comment by animalnots** [comment]
fixed in https://github.com/animalnots/BetterChatGPT-PLUS/releases/tag/v1.9.0
