### ISSUE TITLE
Markdown is broken

### ISSUE THREAD

**Issue by ioannidesalex** [animalnots/BetterChatGPT-PLUS#67]
Latest releases stopped giving responses with markdown. It's just ```

**Comment by animalnots** [comment]
Can you provide replication steps ?
Model, prompt, endpoint (official or not)

**Comment by ioannidesalex** [comment]
Prompt set at default, endpoint is the official one. Happens with all models we have tried.

We just forked your repo and deployed it to GitHub Pages.

**Comment by ioannidesalex** [comment]
Can you please ask it to create e.g. a small Python app? Is the result properly formatted?

**Comment by animalnots** [comment]
Can u click the button in red box and see if it fixes the issue 
![image](https://github.com/user-attachments/assets/d705d793-833b-4a99-ad3a-57b646280a88)

**Comment by ioannidesalex** [comment]
Yes it does! However it was ok by default a few commits ago :)

**Comment by animalnots** [comment]
¯\_(ツ)_/¯

**Comment by ioannidesalex** [comment]
Will you consider this a bug or it will stay as it is?

**Comment by animalnots** [comment]
Well, it depends, it's not a bug but if you want, you can raise a PR to make it customisable in the settings

**Comment by animalnots** [comment]
Doesn't toggling work if you press it once (like keep the behaviour between chats)

**Comment by ioannidesalex** [comment]
Seems to work fine when toggling once. Thank you!
